workspace:
  test:
    monitorFile: C:\111
    ip: localhost
    port: 3316
    user: zs
    password: 111
    uploadPath: /home/zs/upload/
    startCmd:
      - "sudo su"
      - "cd /root"
      - "pwd"
    frontCmd:
    #      - "rm -f /root/1.txt"
    backCmd:
  #      - "rsync -avz /home/zmt/11 /root"
  datax:
  flink: