workspace:
  test:
    monitorFile: C:\Users\simeitol\Desktop\1.txt
    ip: 106.14.150.229
    port: 22
    user: root
    password: Hminde1314
    uploadPath: /root/test/
    startCmd:
      - "ls"
      - "cd /root/test/"
    frontCmd:
      - "ls"
    backCmd:
      - "ls -lh"
  datax:
  flink: