workspace:
  test:
    monitorFile: D:\DataX
    ip: 47.98.208.71
    port: 24260
    user: zmt
    password: 3z6D{f;7vJy~Nw^KXxpv
    uploadPath: /home/zmt/upload/
    startCmd:
      - "sudo su"
      - "cd /root"
      - "pwd"
    frontCmd:
#      - "rm -f /root/1.txt"
    backCmd:
      - "rsync -avz /home/zmt/11 /root"
  datax:
  flink: