workspace:
  test:
    monitorFile: C:\Users\simeitol\Desktop\1.txt
    ip: 47.98.208.71
    port: 24260
    user: zmt
    password: 3z6D{f;7vJy~Nw^KXxpv
    uploadPath: /home/zmt/
    startCmd:
      - "sudo su"
      - "cd /root"
      - "pwd"
    frontCmd:
      - "rm -f /root/1.txt"
    backCmd:
      - "mv /home/zmt/1.txt /root"
  datax:
  flink: